-- 删除TB_CHANNEL(投票频道表 )...
DROP TABLE IF EXISTS TB_CHANNEL;
-- 删除TB_VOTE(投票表 )...
DROP TABLE IF EXISTS TB_VOTE;
-- 删除TB_VOTEOPTION(投票选项表 )...
DROP TABLE IF EXISTS TB_VOTEOPTION;

-- ******************************************************
-- 表名：TB_CHANNEL(投票频道表 )
-- 最后修改日期：
-- 修改说明：
-- ******************************************************
CREATE TABLE TB_CHANNEL (
	CHANNELID			INT(11)				NOT NULL			AUTO_INCREMENT,
	CHANNELNAME			VARCHAR(255)		DEFAULT NULL,
	PRIMARY KEY (CHANNELID)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=GB2312 COMMENT='投票频道表';
ALTER TABLE TB_CHANNEL MODIFY COLUMN CHANNELID INT COMMENT '频道编号';
ALTER TABLE TB_CHANNEL MODIFY COLUMN CHANNELNAME VARCHAR(255) COMMENT '频道名称';

-- ******************************************************
-- 表名：TB_VOTE(投票表 )
-- 最后修改日期：
-- 修改说明：
-- ******************************************************
CREATE TABLE TB_VOTE (
	VOTEID				INT(11)				NOT NULL			AUTO_INCREMENT,
	VOTENAME			VARCHAR(255)		DEFAULT NULL,
	CHANNELID			INT(11)				DEFAULT NULL,
	PRIMARY KEY (VOTEID),
	KEY CHANNELID (CHANNELID)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=GB2312 COMMENT='投票表';
ALTER TABLE TB_VOTE MODIFY COLUMN VOTEID INT COMMENT '投票编号';
ALTER TABLE TB_VOTE MODIFY COLUMN VOTENAME VARCHAR(255) COMMENT '投票名称';
ALTER TABLE TB_VOTE MODIFY COLUMN CHANNELID INT COMMENT '所属频道编号';
ALTER TABLE TB_VOTE ADD CONSTRAINT TB_VOTE_IBFK_1 FOREIGN KEY (CHANNELID) REFERENCES TB_CHANNEL (CHANNELID);

-- ******************************************************
-- 表名：TB_VOTEOPTION(投票表 )
-- 最后修改日期：
-- 修改说明：
-- ******************************************************
CREATE TABLE TB_VOTEOPTION (
	VOTEOPTIONID		INT(11)				NOT NULL			AUTO_INCREMENT,
	VOTEID				INT(11)				DEFAULT NULL,
	VOTEOPTIONNAME		VARCHAR(255)		DEFAULT NULL,
	TICKETNUM			INT(11)				DEFAULT '0',
	PRIMARY KEY (VOTEOPTIONID),
	KEY VOTEID (VOTEID)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=GB2312 COMMENT='投票选项表';
ALTER TABLE TB_VOTEOPTION MODIFY COLUMN VOTEOPTIONID INT COMMENT '投票选项编号';
ALTER TABLE TB_VOTEOPTION MODIFY COLUMN VOTEID INT COMMENT '所属投票编号';
ALTER TABLE TB_VOTEOPTION MODIFY COLUMN VOTEOPTIONNAME VARCHAR(255) COMMENT '投票选项名称';
ALTER TABLE TB_VOTEOPTION MODIFY COLUMN TICKETNUM INT COMMENT '得票数';
ALTER TABLE TB_VOTEOPTION ADD CONSTRAINT TB_VOTEOPTION_IBFK_1 FOREIGN KEY (VOTEID) REFERENCES TB_VOTE (VOTEID);
