-- 删除TB_EMPLOYEE(员工信息表 )...
DROP TABLE IF EXISTS TB_EMPLOYEE;
-- 删除TB_MESSAGE(消息信息表)...
DROP TABLE IF EXISTS TB_MESSAGE;
-- 删除TB_REPLY(消息回复表 )...
DROP TABLE IF EXISTS TB_REPLY;
-- 删除TB_CRITICISM(消息批复表)...
DROP TABLE IF EXISTS TB_CRITICISM;

-- ******************************************************
-- 表名：TB_EMPLOYEE(员工信息表 )
-- 最后修改日期：
-- 修改说明：
-- ******************************************************
CREATE TABLE TB_EMPLOYEE (
	EMPLOYEEID            INT(11)         DEFAULT '0'   NOT NULL ,
	EMPLOYEENAME          VARCHAR(40)     DEFAULT NULL,
	EMPLOYEESEX           BIT(1)          DEFAULT NULL,
	EMPLOYEEBIRTH         DATE            DEFAULT NULL,
	EMPLOYEEPHONE         VARCHAR(20)     DEFAULT NULL,
	EMPLOYEEPLACE         VARCHAR(50)     DEFAULT NULL,
	JOINTIME              DATE            DEFAULT NULL,
	PASSWORD              VARCHAR(20)     DEFAULT NULL,
	ISLEAD                BIT(1)          DEFAULT NULL,
	PRIMARY KEY (EMPLOYEEID)
) ENGINE=InnoDB DEFAULT CHARSET=GB2312 COMMENT='员工信息表';
ALTER TABLE TB_EMPLOYEE MODIFY COLUMN EMPLOYEEID INT COMMENT '员工编号';
ALTER TABLE TB_EMPLOYEE MODIFY COLUMN EMPLOYEENAME VARCHAR(40) COMMENT '员工姓名';
ALTER TABLE TB_EMPLOYEE MODIFY COLUMN EMPLOYEESEX BIT COMMENT '员工性别';
ALTER TABLE TB_EMPLOYEE MODIFY COLUMN EMPLOYEEBIRTH DATE COMMENT '出生日期';
ALTER TABLE TB_EMPLOYEE MODIFY COLUMN EMPLOYEEPHONE VARCHAR(20) COMMENT '联系电话';
ALTER TABLE TB_EMPLOYEE MODIFY COLUMN EMPLOYEEPLACE VARCHAR(50) COMMENT '家庭住址';
ALTER TABLE TB_EMPLOYEE MODIFY COLUMN JOINTIME DATE COMMENT '录入时间';
ALTER TABLE TB_EMPLOYEE MODIFY COLUMN PASSWORD VARCHAR(20) COMMENT '系统口令';
ALTER TABLE TB_EMPLOYEE MODIFY COLUMN ISLEAD BIT COMMENT '是否为管理层领导';

-- ******************************************************
-- 表名：TB_MESSAGE(消息信息表 )
-- 最后修改日期：
-- 修改说明：
-- ******************************************************
CREATE TABLE TB_MESSAGE (
	MESSAGEID             INT(11)            NOT NULL  AUTO_INCREMENT,
	MESSAGETITLE          VARCHAR(50)        DEFAULT NULL,
	MESSAGECONTENT        TEXT,
	EMPLOYEEID            INT(11)            DEFAULT NULL,
	PUBLISHTIME           DATETIME           DEFAULT NULL,
	PRIMARY KEY (MESSAGEID),
	KEY EMPLOYEEID (EMPLOYEEID)
)ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=GB2312 COMMENT='消息信息表';
ALTER TABLE TB_MESSAGE MODIFY COLUMN MESSAGEID INT COMMENT '消息ID';
ALTER TABLE TB_MESSAGE MODIFY COLUMN MESSAGETITLE VARCHAR(50) COMMENT '消息标题';
ALTER TABLE TB_MESSAGE MODIFY COLUMN MESSAGECONTENT TEXT COMMENT '消息内容';
ALTER TABLE TB_MESSAGE MODIFY COLUMN EMPLOYEEID INT COMMENT '发布人';
ALTER TABLE TB_MESSAGE MODIFY COLUMN PUBLISHTIME DATETIME COMMENT '发布时间';
ALTER TABLE TB_MESSAGE ADD CONSTRAINT TB_MESSAGE_IBFK_1 FOREIGN KEY (EMPLOYEEID) REFERENCES TB_EMPLOYEE (EMPLOYEEID);

-- ******************************************************
-- 表名：TB_REPLY(消息回复表 )
-- 最后修改日期：
-- 修改说明：
-- ******************************************************
CREATE TABLE TB_REPLY (
	REPLYID               INT(11)            NOT NULL  AUTO_INCREMENT,
	REPLYCONTENT          TEXT,
	EMPLOYEEID            INT(11)            DEFAULT NULL,
	REPLYTIME             DATETIME           DEFAULT NULL,
	MESSAGEID             INT(11)            DEFAULT NULL,
	PRIMARY KEY (REPLYID),
	KEY EMPLOYEEID (EMPLOYEEID),
	KEY MESSAGEID (MESSAGEID)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=GB2312 COMMENT='消息回复表';
ALTER TABLE TB_REPLY MODIFY COLUMN REPLYID INT COMMENT '消息回复ID';
ALTER TABLE TB_REPLY MODIFY COLUMN REPLYCONTENT TEXT COMMENT '回复内容';
ALTER TABLE TB_REPLY MODIFY COLUMN EMPLOYEEID INT COMMENT '回复人';
ALTER TABLE TB_REPLY MODIFY COLUMN REPLYTIME DATETIME COMMENT '回复时间';
ALTER TABLE TB_REPLY MODIFY COLUMN MESSAGEID INT COMMENT '消息ID';
ALTER TABLE TB_REPLY ADD CONSTRAINT TB_REPLY_IBFK_1 FOREIGN KEY (EMPLOYEEID) REFERENCES TB_EMPLOYEE (EMPLOYEEID),
ADD CONSTRAINT TB_REPLY_IBFK_2 FOREIGN KEY (MESSAGEID) REFERENCES TB_MESSAGE (MESSAGEID);

-- ******************************************************
-- 表名：TB_CRITICISM(消息批复表)
-- 最后修改日期：
-- 修改说明：
-- ******************************************************
CREATE TABLE TB_CRITICISM (
	CRITICISMID               INT(11)            NOT NULL  AUTO_INCREMENT,
	CRITICISMCONTENT          TEXT,
	EMPLOYEEID                INT(11)            DEFAULT NULL,
	CRITICISMTIME             DATETIME           DEFAULT NULL,
	MESSAGEID                 INT(11)            DEFAULT NULL,
	PRIMARY KEY (CRITICISMID),
	KEY EMPLOYEEID (EMPLOYEEID),
	KEY MESSAGEID (MESSAGEID)
)ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=GB2312 COMMENT='消息批复表';
ALTER TABLE TB_CRITICISM MODIFY COLUMN CRITICISMID INT COMMENT '消息批复ID';
ALTER TABLE TB_CRITICISM MODIFY COLUMN CRITICISMCONTENT TEXT COMMENT '批复内容';
ALTER TABLE TB_CRITICISM MODIFY COLUMN EMPLOYEEID INT COMMENT '回复人';
ALTER TABLE TB_CRITICISM MODIFY COLUMN CRITICISMTIME DATETIME COMMENT '批复时间';
ALTER TABLE TB_CRITICISM MODIFY COLUMN MESSAGEID INT COMMENT '消息ID';
ALTER TABLE TB_CRITICISM ADD CONSTRAINT TB_CRITICISM_IBFK_1 FOREIGN KEY (EMPLOYEEID) REFERENCES TB_EMPLOYEE (EMPLOYEEID),
ADD CONSTRAINT TB_CRITICISM_IBFK_2 FOREIGN KEY (MESSAGEID) REFERENCES TB_MESSAGE (MESSAGEID);